# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfers', '0003_auto_20230525_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfboard',
            name='shaper',
        ),
    ]
