# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfers', '0004_remove_surfboard_shaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='shapers',
            field=models.ManyToManyField(related_name='surfboards', to='surfers.Shaper'),
        ),
    ]
