# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfers', '0005_auto_20230525_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='shapers',
            field=models.ManyToManyField(to='surfers.Shaper'),
        ),
    ]
