# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfers', '0006_auto_20230525_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfboardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='surfboard',
            name='surfboard_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surfers.SurfboardModel'),
            preserve_default=False,
        ),
    ]
